# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_category', to='finmancore.Category')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('time_of_transaction', models.DateTimeField()),
                ('is_reconciled', models.BooleanField(default=False)),
                ('currency', models.CharField(blank=True, default=None, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finmancore.Transaction')),
                ('from_account', models.CharField(max_length=500)),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credited_account', to='finmancore.Account')),
            ],
            bases=('finmancore.transaction',),
        ),
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finmancore.Transaction')),
                ('to_account', models.CharField(max_length=500)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debited_account', to='finmancore.Account')),
            ],
            bases=('finmancore.transaction',),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finmancore.Transaction')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='finmancore.Account')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='finmancore.Account')),
            ],
            bases=('finmancore.transaction',),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='finmancore.Category'),
        ),
    ]
